export const STORAGE_KEYS = {
  token: 'xinchat.token',
  chatDeviceId: 'xinchat.chatDeviceId',
  chatDeviceCreatedAtMs: 'xinchat.chatDeviceCreatedAtMs',
  profile: 'xinchat.profile',
  readAt: 'xinchat.readAt',
  chatDeleteCutoff: 'xinchat.chatDeleteCutoff',
  pinned: 'xinchat.pinned',
  hiddenChats: 'xinchat.hiddenChats',
  homeTourSeen: 'xinchat.homeTourSeen',
  pendingOpenChat: 'xinchat.pendingOpenChat',
  homeFriendsCache: 'xinchat.homeFriendsCache',
  homeGroupsCache: 'xinchat.homeGroupsCache',
  homeMessagesCache: 'xinchat.homeMessagesCache',
  homeLatestCache: 'xinchat.homeLatestCache',
  homeUnreadCache: 'xinchat.homeUnreadCache',
  homePendingRequestsCache: 'xinchat.homePendingRequestsCache',
  chatMuted: 'xinchat.chatMuted',
  chatBackground: 'xinchat.chatBackground',
  customStickersPrefix: 'xinchat.customStickers.',
  favoriteMessagesPrefix: 'xinchat.favoriteMessages.',
  messageRemindersPrefix: 'xinchat.messageReminders.',
  groupRemarks: 'xinchat.groupRemarks',
  pendingChatSettingsAction: 'xinchat.pendingChatSettingsAction',
} as const;

